# Generated by Django 3.2.5 on 2021-08-22 05:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '类别管理', 'verbose_name_plural': '类别管理'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '文章详情', 'verbose_name_plural': '文章管理'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签管理', 'verbose_name_plural': '标签管理'},
        ),
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='article_img/%Y/%m/%d/', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文'),
        ),
    ]
