# Generated by Django 3.2 on 2021-11-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_auto_20210822_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='index',
            field=models.IntegerField(default=1, verbose_name='分类排序'),
        ),
    ]
